# Generated by Django 5.2.5 on 2025-08-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='username',
            field=models.CharField(default='anonymous', max_length=50),
        ),
    ]
